server:
  port: 8080
#  servlet:
#    context-path: /api
logging:
  level:
    root: info
    com.milly: debug
  file:
    name: logs/debug.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: YAya0408
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true




